### ISSUE TITLE
Computed throughput in UI is inconsistent

### ISSUE THREAD

**Issue by abailly-iohk** [input-output-hk/ouroboros-leios#10] opened 2024-08-01 07:30 UTC
I have polished a bit the UI and added some metrics, but those don't make sense to me: I would expected throughput, computed as the total amount of endorsed data divided by time to be in the order of $C \lambda / (\lambda + 1)$ but this is not the case.

![Screenshot 2024-07-18 at 15 24 27](https://github.com/user-attachments/assets/e199bc5b-2efd-4e74-872e-69fcf406ab7c)

I think this is an artifact stemming from 2 sources:
* The throughput does not distinguish between the 2 nodes 
* The parameters $f_I$ and $f_E$ are too large, so we are producing unrealistically too many blocks

**Comment by RenateEilers** [comment] 2024-08-08 09:37
The issue was caused by the data of a single IB being counted towards throughput twice by every EB referencing it (so up to four times if both nodes produce an EB in the same slice). This bug was fixed in f497b29fd24e350c7f942282e60214f40b755d7b. 

The throughput is now roughly equal to $\min(C,f_{I} |IB|)$, since the network in the simulation is complete and all new IB data is immediately available. Capping the IB data rate below $C \frac{\lambda}{\lambda + 1}$ should become relevant when the network diameter grows.

![Screenshot from 2024-08-08 11-40-17](https://github.com/user-attachments/assets/982cc01b-91a1-485c-a1d5-58f4be6a8bfe)

**Comment by RenateEilers** [comment] 2024-08-08 09:41
The issue was caused by the data of a single IB being counted towards throughput twice by every EB referencing it (so up to four times if both nodes produce an EB in the same slice). This bug was fixed in f497b29fd24e350c7f942282e60214f40b755d7b. 

The throughput is now roughly equal to $\min(C,f_{I} |IB|)$, since the network in the simulation is complete and all new IB data is immediately available. Capping the IB data rate below $C \frac{\lambda}{\lambda + 1}$ should become relevant when the network diameter grows.

![Screenshot from 2024-08-08 11-40-17](https://github.com/user-attachments/assets/4f69c9ef-7431-402d-a9e1-8567bcea24df)

**Closed by RenateEilers** 2024-08-08 09:41 UTC
